# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"

    filter_sets:
        products_list:
            filters:
                thumbnail: { size: [250, 250], mode: outbound}
                background: { size: [250, 250], position: center, color: '#ffffff' }


